# Generated by Django 3.2.6 on 2021-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(default='nopic.jpg', upload_to=''),
        ),
    ]
