# Generated by Django 3.2.6 on 2021-09-25 04:57

from django.db import migrations, models
import django.db.models.manager
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_cover_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_manager_name': 'query'},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(default='nopic.jpg', upload_to=posts.models.Post.generate_cover_pic_path),
        ),
    ]
